workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - fadlmoh632@gmail.com
