name: my_calculator
description: A simple calculator app without external packages.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.5.0
  collection: ^1.19.2
  material_color_utilities: ^0.13.1
  meta: ^1.17.0
  vector_math: 2.1.4
